{{ if .Values.createWebsocketsCertificate -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "polkadot-deployer.certificateName" . }}
spec:
  secretName: {{ include "polkadot-deployer.tlsSecretName" . }}
  issuerRef:
    name: letsencrypt-{{ .Values.chainSpecName }}
    kind: ClusterIssuer
  dnsNames:
  - {{ include "polkadot-deployer.websocketsDomain" . }}
{{ end }}
---
{{- if .Values.monitoring }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grafana-{{ .Values.chainSpecName }}-tls
  namespace: {{ .Values.grafana.namespace }}
spec:
  secretName: {{ include "polkadot-deployer.grafanaTlsSecretName" . }}
  issuerRef:
    name: letsencrypt-{{ .Values.chainSpecName }}
    kind: ClusterIssuer
  dnsNames:
  - {{ include "polkadot-deployer.grafanaDomain" . }}
{{ end }}
