{{ if .Values.createCertIssuer -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.chainSpecName }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@web3.foundation

    privateKeySecretRef:
      name: letsencrypt

    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.cloudflareEmail }}
          apiKeySecretRef:
            name: cloudflare-credentials
            key: api-key
{{ end }}
