{{ if .Values.createWebsocketsIngress -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-websockets
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
      - {{ include "polkadot-deployer.websocketsDomain" . }}
    secretName: {{ include "polkadot-deployer.tlsSecretName" . }}
  rules:
  - host: {{ include "polkadot-deployer.websocketsDomain" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "polkadot-deployer.websocketService" . }}
            port:
              number: 9944
{{ end }}
